//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctxmgr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ctxmgr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register the global hotkey {0}.
        /// </summary>
        public static string AltZRegistrationFailed {
            get {
                return ResourceManager.GetString("AltZRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Background Color.
        /// </summary>
        public static string BgColor {
            get {
                return ResourceManager.GetString("BgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BgColorWindowTitle {
            get {
                return ResourceManager.GetString("BgColorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find {0}.
        /// </summary>
        public static string CantFind {
            get {
                return ResourceManager.GetString("CantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonly used for summarization and extraction..
        /// </summary>
        public static string capability_summarization {
            get {
                return ResourceManager.GetString("capability_summarization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change HotKey fail!,Reset to default!.
        /// </summary>
        public static string ChangeHotkeyFail {
            get {
                return ResourceManager.GetString("ChangeHotkeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Hotkey success!.
        /// </summary>
        public static string ChangeHotkeySuccess {
            get {
                return ResourceManager.GetString("ChangeHotkeySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ch_oose Folder &amp; Files....
        /// </summary>
        public static string ChooseFolderFiles {
            get {
                return ResourceManager.GetString("ChooseFolderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Folder &amp; Files.
        /// </summary>
        public static string ChooseFolderFilesWindowTitle {
            get {
                return ResourceManager.GetString("ChooseFolderFilesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDeleteMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied the context to the clipboard!.
        /// </summary>
        public static string ContextCopiedSuccessfully {
            get {
                return ResourceManager.GetString("ContextCopiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register the global hotkey Ctrl+Q.
        /// </summary>
        public static string CtrlQRegistrationFailed {
            get {
                return ResourceManager.GetString("CtrlQRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (_X).
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On double-clicking page title.
        /// </summary>
        public static string DblClickTitleAction {
            get {
                return ResourceManager.GetString("DblClickTitleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page.
        /// </summary>
        public static string DblClickTitleActionDelete {
            get {
                return ResourceManager.GetString("DblClickTitleActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string DblClickTitleActionNone {
            get {
                return ResourceManager.GetString("DblClickTitleActionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename title.
        /// </summary>
        public static string DblClickTitleActionRename {
            get {
                return ResourceManager.GetString("DblClickTitleActionRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultPageTitle {
            get {
                return ResourceManager.GetString("DefaultPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string DeleteWindowTitle {
            get {
                return ResourceManager.GetString("DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Page.
        /// </summary>
        public static string DelTab {
            get {
                return ResourceManager.GetString("DelTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 ​Double-click a file to check/uncheck it.​.
        /// </summary>
        public static string DoubleClickFile {
            get {
                return ResourceManager.GetString("DoubleClickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Double-click on a folder to expand or collapse its subnodes..
        /// </summary>
        public static string DoubleClickFolder {
            get {
                return ResourceManager.GetString("DoubleClickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Page Title.
        /// </summary>
        public static string EditTabTitle {
            get {
                return ResourceManager.GetString("EditTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating shortcut..
        /// </summary>
        public static string ErrorCreatingShotcut {
            get {
                return ResourceManager.GetString("ErrorCreatingShotcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when setting auto-start.
        /// </summary>
        public static string ErrorSettingAutoStart {
            get {
                return ResourceManager.GetString("ErrorSettingAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Previous.
        /// </summary>
        public static string FindPrev {
            get {
                return ResourceManager.GetString("FindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindWindowTitle {
            get {
                return ResourceManager.GetString("FindWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string FontBold {
            get {
                return ResourceManager.GetString("FontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string FontItalic {
            get {
                return ResourceManager.GetString("FontItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview font effects: The quick brown fox jumps over the lazy dog..
        /// </summary>
        public static string FontPreview {
            get {
                return ResourceManager.GetString("FontPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontSettingsWindowTitle {
            get {
                return ResourceManager.GetString("FontSettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string FontUnderLine {
            get {
                return ResourceManager.GetString("FontUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_ormat.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start automatically when system boots.
        /// </summary>
        public static string GeneralAutoStart {
            get {
                return ResourceManager.GetString("GeneralAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize when closing the main window.
        /// </summary>
        public static string GeneralCloseToTray {
            get {
                return ResourceManager.GetString("GeneralCloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Options.
        /// </summary>
        public static string GeneralOptions {
            get {
                return ResourceManager.GetString("GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Context.
        /// </summary>
        public static string GenerateContext {
            get {
                return ResourceManager.GetString("GenerateContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Context.
        /// </summary>
        public static string GenerateCtx {
            get {
                return ResourceManager.GetString("GenerateCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide Esc.
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window.
        /// </summary>
        public static string HideWindow2 {
            get {
                return ResourceManager.GetString("HideWindow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert _Date/Time.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert DateTime Format.
        /// </summary>
        public static string InsertDateTimeFormat {
            get {
                return ResourceManager.GetString("InsertDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date/Time Separator(_B).
        /// </summary>
        public static string InsertDateTimeSeparator {
            get {
                return ResourceManager.GetString("InsertDateTimeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert DateTime Separator Format.
        /// </summary>
        public static string InsertDateTimeSeparatorFormat {
            get {
                return ResourceManager.GetString("InsertDateTimeSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Separator _Line.
        /// </summary>
        public static string InsertSeparator {
            get {
                return ResourceManager.GetString("InsertSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Separator Line format.
        /// </summary>
        public static string InsertSeparatorFormat {
            get {
                return ResourceManager.GetString("InsertSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text Setting(_C).
        /// </summary>
        public static string InsertTextSetting {
            get {
                return ResourceManager.GetString("InsertTextSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load from File.
        /// </summary>
        public static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left(_L).
        /// </summary>
        public static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right(_R).
        /// </summary>
        public static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Leftmost(_F).
        /// </summary>
        public static string MoveToLeftMost {
            get {
                return ResourceManager.GetString("MoveToLeftMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Rightmost(_A).
        /// </summary>
        public static string MoveToRightMost {
            get {
                return ResourceManager.GetString("MoveToRightMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​Enter new snippet​.
        /// </summary>
        public static string NewSnippetPlaceholder {
            get {
                return ResourceManager.GetString("NewSnippetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Page.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Found.
        /// </summary>
        public static string NoMoreFound {
            get {
                return ResourceManager.GetString("NoMoreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt|All File (*.*)|*.*.
        /// </summary>
        public static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plugin.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Prompt: Write a prompt for my AI coding agent. Split the tasks into sub-tasks with enough detail to guide the agent. The agent might not be very smart but you can guide it along using plain English and find / replace style text, include just enough details to guide the agent and include some of the &apos;whys&apos; about why we are doing what we are doing, to help guide it along. Enclose the entire agent prompt in one big code tag for easy copy and paste. .
        /// </summary>
        public static string PredefineAgentPrompt {
            get {
                return ResourceManager.GetString("PredefineAgentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Practices: Please analyze this code for: Error handling, Edge cases, Performance optimization, Best practices, Please do not unnecessarily remove any comments or code. Generate the code with clear comments explaining the logic..
        /// </summary>
        public static string PredefineBestPractices {
            get {
                return ResourceManager.GetString("PredefineBestPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review for: Code quality and adherence to best practices, Potential bugs or edge cases, Performance optimizations, Readability and maintainability, Security concerns. Suggest improvements and explain your reasoning for each suggestion.
        /// </summary>
        public static string PredefineCodeReview {
            get {
                return ResourceManager.GetString("PredefineCodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cline, Roo Code Prompt: Write a prompt for Cline, an AI coding agent, to make the necessary changes. Enclose the entire Cline prompt in one single code tag for easy copy and paste. Cline likes search and replace blocks with just plain language with a little bit of explanations about why we are doing things to help guide the agent..
        /// </summary>
        public static string PredefineCodingPrompt {
            get {
                return ResourceManager.GetString("PredefineCodingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug:Can you help me debug this code?.
        /// </summary>
        public static string PredefineDebug {
            get {
                return ResourceManager.GetString("PredefineDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityCheck: Can you analyze this code for any security issues?.
        /// </summary>
        public static string PredefineSecurityCheck {
            get {
                return ResourceManager.GetString("PredefineSecurityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prompt At Footer.
        /// </summary>
        public static string PromptAtFooter {
            get {
                return ResourceManager.GetString("PromptAtFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prompt At Header.
        /// </summary>
        public static string PromptAtHeader {
            get {
                return ResourceManager.GetString("PromptAtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonly used for Q&amp;A and code generation..
        /// </summary>
        public static string qa_and_code {
            get {
                return ResourceManager.GetString("qa_and_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_do.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All to default.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run On _StartUp.
        /// </summary>
        public static string RunOnStartUp {
            get {
                return ResourceManager.GetString("RunOnStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save to File.
        /// </summary>
        public static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt|All File (*.*)|*.*.
        /// </summary>
        public static string SaveToFileFilter {
            get {
                return ResourceManager.GetString("SaveToFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings(_S).
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Z: Show/Hide the main window   (Customizable)
        ///Esc: Hide the window  
        ///Ctrl+Q: Send selected content to the current tab  
        ///Ctrl+F: Find.
        /// </summary>
        public static string ShortcutAllList {
            get {
                return ResourceManager.GetString("ShortcutAllList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Shortcut List.
        /// </summary>
        public static string ShortcutList {
            get {
                return ResourceManager.GetString("ShortcutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide main window shortcut.
        /// </summary>
        public static string ShortcutsShowOrHide {
            get {
                return ResourceManager.GetString("ShortcutsShowOrHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic key.
        /// </summary>
        public static string ShortcutsShowOrHideBasicKey {
            get {
                return ResourceManager.GetString("ShortcutsShowOrHideBasicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination key.
        /// </summary>
        public static string ShortcutsShowOrHideCombineKey {
            get {
                return ResourceManager.GetString("ShortcutsShowOrHideCombineKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show WIndow.
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Description(_R).
        /// </summary>
        public static string SoftwareDescription {
            get {
                return ResourceManager.GetString("SoftwareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful add !.
        /// </summary>
        public static string SuccessfulAdd {
            get {
                return ResourceManager.GetString("SuccessfulAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Title.
        /// </summary>
        public static string TabTitleEditor {
            get {
                return ResourceManager.GetString("TabTitleEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jot something down.
        /// </summary>
        public static string TextBoxHint {
            get {
                return ResourceManager.GetString("TextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert text snippet.
        /// </summary>
        public static string TextSnippets {
            get {
                return ResourceManager.GetString("TextSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TextSnippetsAdd {
            get {
                return ResourceManager.GetString("TextSnippetsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​Custom Snippets​.
        /// </summary>
        public static string TextSnippetsCustom {
            get {
                return ResourceManager.GetString("TextSnippetsCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextSnippetsDel {
            get {
                return ResourceManager.GetString("TextSnippetsDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TextSnippetsEdit {
            get {
                return ResourceManager.GetString("TextSnippetsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Word Wrap.
        /// </summary>
        public static string TextWrap {
            get {
                return ResourceManager.GetString("TextWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Topmost.
        /// </summary>
        public static string ToggleTopmost {
            get {
                return ResourceManager.GetString("ToggleTopmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ctxmgr.com.
        /// </summary>
        public static string VisitOfficialWebsite {
            get {
                return ResourceManager.GetString("VisitOfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
